apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overpass-api.fullname" . }}
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiService.replicaCount }}
  selector:
    matchLabels:
      {{- include "overpass-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "overpass-api.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-db
        image: "{{ .Values.apiService.image.repository }}:{{ .Chart.AppVersion }}"
        command: 
        - /bin/sh
        - -c
        - |
          if [ ! -f /app/db/replicate_id ]; then
            echo "Database not found. Waiting for initialization job to complete..."
            while [ ! -f /app/db/replicate_id ]; do
              sleep 10
            done
          fi
          echo "Database is ready."
        volumeMounts:
        - name: data
          mountPath: /app/db
          readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.apiService.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiService.image.pullPolicy }}
          env:
          - name: OVERPASS_MODE
            value: "readonly"
          - name: OVERPASS_META
            value: {{ .Values.overpassMeta | quote }}
          - name: OVERPASS_FASTCGI_PROCESSES
            value: {{ .Values.apiService.fastcgiProcesses | quote }}
          - name: OVERPASS_RATE_LIMIT
            value: {{ .Values.apiService.rateLimit | quote }}
          - name: OVERPASS_TIME
            value: {{ .Values.apiService.time | quote }}
          - name: OVERPASS_SPACE
            value: {{ .Values.apiService.space | quote }}
          - name: OVERPASS_MAX_TIMEOUT
            value: {{ .Values.apiService.maxTimeout | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /app/db
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "overpass-api.fullname" . }}-data