apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overpass-api.fullname" . }}
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiService.replicaCount }}
  selector:
    matchLabels:
      {{- include "overpass-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "overpass-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "overpass-api.fullname" . }}-sa
      initContainers:
      - name: wait-for-init-job
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for init job to complete..."
          while ! kubectl get job {{ include "overpass-api.fullname" . }}-init -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep -q True; do
            sleep 10
          done
          echo "Init job completed"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.apiService.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiService.image.pullPolicy }}
          env:
          - name: OVERPASS_MODE
            value: "readonly"
          - name: OVERPASS_META
            value: {{ .Values.overpassMeta | quote }}
          - name: OVERPASS_FASTCGI_PROCESSES
            value: {{ .Values.apiService.fastcgiProcesses | quote }}
          - name: OVERPASS_RATE_LIMIT
            value: {{ .Values.apiService.rateLimit | quote }}
          - name: OVERPASS_TIME
            value: {{ .Values.apiService.time | quote }}
          - name: OVERPASS_SPACE
            value: {{ .Values.apiService.space | quote }}
          - name: OVERPASS_MAX_TIMEOUT
            value: {{ .Values.apiService.maxTimeout | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /app/db
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "overpass-api.fullname" . }}-data