apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "overpass-api.fullname" . }}-init
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "overpass-api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "overpass-api.fullname" . }}-sa
      initContainers:
      - name: wait-for-pvc
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for PVC to be bound..."
          until kubectl get pvc {{ include "overpass-api.fullname" . }}-data -o jsonpath='{.status.phase}' | grep -q Bound; do
            sleep 5
          done
          echo "PVC is bound"
      containers:
      - name: overpass-init
        image: "{{ .Values.updateJob.image.repository }}:{{ .Values.updateJob.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.updateJob.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          if [ -z "$(ls -A /app/db)" ]; then
            echo "Volume is empty, initializing..."
            OVERPASS_MODE=update /app/update_overpass.sh
          else
            echo "Volume already initialized"
          fi
        env:
        - name: OVERPASS_META
          value: {{ .Values.overpassMeta | quote }}
        - name: OVERPASS_PLANET_URL
          value: {{ .Values.updateJob.planetUrl | quote }}
        - name: OVERPASS_DIFF_URL
          value: {{ .Values.updateJob.diffUrl | quote }}
        - name: OVERPASS_UPDATE_FREQUENCY
          value: {{ .Values.updateJob.updateFrequency | quote }}
        - name: OVERPASS_COMPRESSION
          value: {{ .Values.overpassCompression | quote }}
        - name: OVERPASS_RULES_LOAD
          value: {{ .Values.updateJob.rulesLoad | quote }}
        volumeMounts:
        - name: data
          mountPath: /app/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "overpass-api.fullname" . }}-data