apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "overpass-api.fullname" . }}-init
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "overpass-api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: overpass-init
        image: "{{ .Values.updateJob.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.updateJob.image.pullPolicy }}
        env:
        - name: OVERPASS_MODE
          value: "update"
        - name: OVERPASS_META
          value: {{ .Values.overpassMeta | quote }}
        - name: OVERPASS_PLANET_URL
          value: {{ .Values.updateJob.planetUrl | quote }}
        - name: OVERPASS_DIFF_URL
          value: {{ .Values.updateJob.diffUrl | quote }}
        - name: OVERPASS_UPDATE_FREQUENCY
          value: {{ .Values.updateJob.updateFrequency | quote }}
        - name: OVERPASS_COMPRESSION
          value: {{ .Values.overpassCompression | quote }}
        - name: OVERPASS_RULES_LOAD
          value: {{ .Values.updateJob.rulesLoad | quote }}
        volumeMounts:
        - name: data
          mountPath: /app/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "overpass-api.fullname" . }}-data