apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "overpass-api.fullname" . }}-sa
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "overpass-api.fullname" . }}-role
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "overpass-api.fullname" . }}-rolebinding
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "overpass-api.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "overpass-api.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io