apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "overpass-api.fullname" . }}
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "overpass-api.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "overpass-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "overpass-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "overpass-api.fullname" . }}-sa
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-overpass-data
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - /scripts/init_overpass.sh
          volumeMounts:
          - name: data
            mountPath: /app/db
          - name: data
            mountPath: /app/work
          - name: scripts
            mountPath: /scripts
          env:
          - name: BOO_OVERPASS_PLANET_URL
            value: "{{ .Values.overpass.planetUrl }}"
          - name: BOO_OVERPASS_META
            value: "{{ .Values.overpass.meta }}"
          - name: BOO_OVERPASS_COMPRESSION
            value: "{{ .Values.overpass.compression }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - /scripts/run_overpass.sh
          env:
          - name: BOO_OVERPASS_META
            value: {{ .Values.overpass.meta | quote }}
          - name: BOO_OVERPASS_FASTCGI_PROCESSES
            value: {{ .Values.overpass.fastcgiProcesses | quote }}
          - name: BOO_OVERPASS_RATE_LIMIT
            value: {{ .Values.overpass.rateLimit | quote }}
          - name: BOO_OVERPASS_TIME
            value: {{ .Values.overpass.time | quote }}
          - name: BOO_OVERPASS_SPACE
            value: {{ .Values.overpass.space | quote }}
          - name: BOO_OVERPASS_MAX_TIMEOUT
            value: {{ .Values.overpass.maxTimeout | quote }}
          - name: BOO_OVERPASS_PLANET_URL
            value: {{ .Values.overpass.planetUrl | quote }}
          - name: BOO_OVERPASS_DIFF_URL
            value: {{ .Values.overpass.diffUrl | quote }}
          - name: BOO_OVERPASS_UPDATE_FREQUENCY
            value: {{ .Values.overpass.updateFrequency | quote }}
          - name: BOO_OVERPASS_COMPRESSION
            value: {{ .Values.overpass.compression | quote }}
          - name: BOO_OVERPASS_RULES_LOAD
            value: {{ .Values.overpass.rulesLoad | quote }}
          - name: BOO_OVERPASS_ALLOW_DUPLICATE_QUERIES
            value: {{ .Values.overpass.allowDuplicateQueries | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /app/db
          - name: data
            mountPath: /app/work
          - name: scripts
            mountPath: /scripts
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /scripts/health_check.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /scripts/health_check.sh
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: scripts
        configMap:
          name: {{ include "overpass-api.fullname" . }}-scripts
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}