name: Publish Helm Chart

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - "charts/**"

env:
  DOCKER_REPO: remikalbe/overpass-api-kube

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important parameter

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Extract version from Chart.yaml
        run: |
          VERSION=$(grep 'version:' charts/overpass-api-chart/Chart.yaml | awk '{print $2}' | tr -d '"')
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.4.0/chart-releaser_1.4.0_linux_amd64.tar.gz
          tar -xzf chart-releaser_1.4.0_linux_amd64.tar.gz
          sudo mv cr /usr/local/bin/cr

      - name: Package Helm chart
        run: |
          helm package charts/overpass-api-chart

      - name: Create release and upload chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr upload \
            --owner ${{ github.repository_owner }} \
            --git-repo ${{ github.event.repository.name }} \
            --package-path ./overpass-api-chart-${{ env.NEW_VERSION }}.tgz

      - name: Update Helm repository index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr index \
            --owner ${{ github.repository_owner }} \
            --git-repo ${{ github.event.repository.name }} \
            --pages-branch gh-pages \
            --push

      - name: Tag and/or release exist
        id: check-tag
        run: |
          set -o pipefail

          # Check for tag
          TAG_EXISTS=$(git tag | grep -c "chart-${{ env.NEW_VERSION }}" || echo 0)

          # Check for release
          RELEASE_EXISTS=$(gh release list --repo ${{ github.repository }} | grep -c "${{ env.NEW_VERSION }}" || echo 0)

          echo "TAG_EXISTS: $TAG_EXISTS"
          echo "RELEASE_EXISTS: $RELEASE_EXISTS"

          if [ "$TAG_EXISTS" -gt "0" ] && [ "$RELEASE_EXISTS" -gt "0" ]; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
            echo "Both tag and release exist"
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
            echo "Either tag or release does not exist"
          fi

      - name: Create Tag
        if: steps.check-tag.outputs.tag_exists == 'false'
        run: |
          git tag chart-${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}

      - name: Create Release
        if: steps.check-tag.outputs.tag_exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: Overpass API Helm Chart ${{ env.NEW_VERSION }}
          tag_name: chart-${{ env.NEW_VERSION }}
          body: |
            This release contains the official Overpass API Helm Chart version ${{ env.NEW_VERSION }}.

          draft: false
          prerelease: false
          generate_release_notes: true
