name: Publish Helm Chart

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - "overpass-api-chart/**"

env:
  DOCKER_REPO: your-docker-repo/overpass
  HELM_REPO: ghcr.io/${{ github.repository_owner }}/overpass-api-chart

defaults:
  run:
    working-directory: overpass-api-chart

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Package Helm chart
        run: |
          helm package .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart
        run: |
          helm push overpass-api-*.tgz oci://${{ env.HELM_REPO }}

      - name: Update Helm repository index
        run: |
          helm repo index --url ${{ env.HELM_REPO }} .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.yaml
          git commit -m "Update Helm repository index"
          git push
