name: Build & Publish image

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "health_check.sh"
      - "run_overpass.sh"
      - "nginx.conf"
      - ".github/workflows/publish-image.yaml"
  pull_request:
    types: [closed]

env:
  DOCKER_REPO: remikalbe/overpass-api-kube
  HELM_REPO: ghcr.io/${{ github.repository_owner }}/overpass-api-helm-chart

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            VERSION=$(echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | jq -r '.[] | select(startswith("image-")) | sub("image-"; "")')
            OVERPASS_VERSION=$(echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | jq -r '.[] | select(startswith("overpass-")) | sub("overpass-"; "")')
          else
            VERSION=$(yq e '.appVersion' charts/overpass-api-chart/Chart.yaml)
            OVERPASS_VERSION=$(echo $VERSION | cut -d'.' -f1-3)
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "OVERPASS_VERSION=${OVERPASS_VERSION}" >> $GITHUB_OUTPUT

      - name: Check if image exists
        id: check_image
        run: |
          EXISTS=$(docker manifest inspect ${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }} > /dev/null && echo "true" || echo "false")
          echo "EXISTS=${EXISTS}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.check_image.outputs.EXISTS == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: steps.check_image.outputs.EXISTS == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check_image.outputs.EXISTS == 'false' || github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.DOCKER_REPO }}:latest

      - name: Set as latest (only for PRs)
        if: github.event_name == 'pull_request' && steps.check_image.outputs.EXISTS == 'true'
        run: |
          docker pull ${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }}
          docker tag ${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }} ${{ env.DOCKER_REPO }}:latest
          docker push ${{ env.DOCKER_REPO }}:latest

      - name: Create Release
        if: steps.check_image.outputs.EXISTS == 'false' || github.event_name == 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          name: overpass-api-image-${{ steps.get_version.outputs.VERSION }}
          tag_name: image-${{ steps.get_version.outputs.VERSION }}
          body: |
            This release contains version ${{ steps.get_version.outputs.VERSION }} of the Overpass API image.
            And version ${{ steps.get_version.outputs.OVERPASS_VERSION }} of the Overpass API.

          draft: false
          prerelease: false
          generate_release_notes: true
