name: Build new image from upstream updates and create PR

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

env:
  DOCKER_REPO: remikalbe/overpass-api-kube

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Check for new Overpass API version
        id: check-version
        working-directory: charts/overpass-api-chart
        run: |
          LATEST_VERSION=$(curl -s https://dev.overpass-api.de/releases/ | grep -oP 'osm-3s_v\K[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n1)
          CURRENT_VERSION=$(yq e '.appVersion' Chart.yaml | cut -d'.' -f1-3)
          echo "Latest version: $LATEST_VERSION"
          echo "Current version: $CURRENT_VERSION"
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "NEW_VERSION=$LATEST_VERSION.0" >> $GITHUB_ENV
            echo "OVERPASS_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for existing PR
        if: steps.check-version.outputs.version_changed == 'true'
        id: check-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --search "Update Overpass API to version ${{ env.NEW_VERSION }}" --json number --jq length)
          if [ "$PR_EXISTS" -gt "0" ]; then
            echo "::set-output name=pr_exists::true"
          else
            echo "::set-output name=pr_exists::false"
          fi

      - name: Update Chart.yaml
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        run: |
          yq e '.appVersion = "'"${{ env.NEW_VERSION }}"'"' -i charts/overpass-api-chart/Chart.yaml

      - name: Set up QEMU
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Overpass image
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.NEW_VERSION }}
          build-args: |
            OVERPASS_VERSION=${{ env.OVERPASS_VERSION }}

      - name: Commit changes
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add charts/overpass-api-chart/Chart.yaml
          git commit -m "Update Overpass API to version ${{ env.NEW_VERSION }}"
          git push --set-upstream origin update-overpass-api-${{ env.NEW_VERSION }}

      - name: Create Pull Request
        if: steps.check-version.outputs.version_changed == 'true' && steps.check-pr.outputs.pr_exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY="This PR updates the Overpass API version to ${{ env.NEW_VERSION }}.

          Changes:
          - Updated appVersion in Chart.yaml to ${{ env.NEW_VERSION }}
          - Incremented chart version
          - Built and pushed new Docker image with Overpass API ${{ env.OVERPASS_VERSION }}

          Please review and approve."

          gh pr create --title "Update Overpass API to version ${{ env.NEW_VERSION }}" \
                        --body "$PR_BODY" \
                        --base main \
                        --head update-overpass-api-${{ env.NEW_VERSION }} \
                        --label "overpass-api-update" \
                        --label "v-${{ env.NEW_VERSION }}"
